language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bwillou/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true bwillou/docker-react2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: docker-react2
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-2-688454921726
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"