language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bwillou/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true bwillou/docker-react2 npm run test